[package]
name = "payment"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = "2.8.0"
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
openzeppelin_utils = "1.0.0"
snforge_std = "0.41.0"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true
